Models/Attachment.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.Models
{
    public class Attachment
    {
        [Key]
        public Guid AttachmentId { get; set; }        
        [Required]
        public string Path { get; set; }
        [Required]
        public string FileName { get; set; }        
        public DateTime EntryDate { get; set; } = DateTime.Now;
       
    }
}

Models/CultureSwitcherModel.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.Models
{
    public class CultureSwitcherModel
    {
        public CultureInfo CurrentUICulture { get; set; }
        public List<CultureInfo> SupportedCultures { get; set; }
        
    }
}

Models/ErrorViewModel.cs
using System;

namespace WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/Api/AttachmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebUI.Interface;
using WebUI.Models;

namespace WebUI.Controllers.Api
{
    [Route("api/v1/[controller]")]
    [ApiController]

    public class AttachmentController : ControllerBase
    {
        private IAttachmentRepository _repo;
        public AttachmentController(IAttachmentRepository repo)
        {
            _repo = repo;
        }

        //Post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create1(Attachment attachment)
        {
            if (ModelState.IsValid)
            {
               
                await _repo.CreateSync(attachment);
                return CreatedAtAction(nameof(Index), new { id = attachment.AttachmentId }, attachment);
            }
            return BadRequest(ModelState);
        }

        
    }
}

Controllers/AttachmentController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebUI.Interface;
using WebUI.Models;
using WebUI.ViewModel;

namespace WebUI.Controllers
{
    //[Route("api/v1/[controller]")]
    //[ApiController]

    public class AttachmentController : Controller //: ControllerBase 
    {
        //Injection interface to the controller 
        private IAttachmentRepository _repo;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public AttachmentController (IAttachmentRepository repo, IWebHostEnvironment webHostEnvironment)
        {
            _repo = repo;
            _webHostEnvironment = webHostEnvironment;
        }

        //[HttpGet]
        //[Route("GetAll")]
        public async Task<IActionResult> Index()//[FromQuery] Models.PurchaseRequisition.PurchaseRequisition pr
        {
            var pa = await _repo.GetAllSync();
            //return Ok(pa);
            return View(pa);
        }

        //UI Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        public async Task<IActionResult> Add()
        {
            return View();
        }

        //Post Create
        [HttpPost]
        //to prevent from malicious command or script from trusted browser
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AttachmentViewModel model)
        {            
            if (ModelState.IsValid)
            {
                Attachment attachment = new Attachment
                {                    
                    FileName = UploadedFile(model),
                    Path = Path.Combine(_webHostEnvironment.WebRootPath, "images")
            };

                await _repo.CreateSync(attachment);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        //storing attachment in the table 
        private string UploadedFile(AttachmentViewModel model)
        {
            string fileName = null;           

            if (model.FileName != null)
            {
                //Images folder in the project where storing all the files 
                //to display the path 
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                //if need to store with uniquename
                //uniqueFileName = Guid.NewGuid().ToString() + "_" + model.FileName.FileName;
                fileName = model.FileName.FileName;
                string filePath = Path.Combine(uploadsFolder, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.FileName.CopyTo(fileStream);
                }
            }
            return fileName;
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ViewComponents/CultureSwitcherViewComponent.cs
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebUI.Models;

namespace WebUI.ViewComponents
{
    public class CultureSwitcherViewComponent : ViewComponent
    {
        private readonly IOptions<RequestLocalizationOptions> localizationOptions;
        public CultureSwitcherViewComponent(IOptions<RequestLocalizationOptions> localizationOptions) =>
            this.localizationOptions = localizationOptions;

        public IViewComponentResult Invoke()
        {
            var cultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
            var model = new CultureSwitcherModel
            {
                SupportedCultures = localizationOptions.Value.SupportedUICultures.ToList(),
                CurrentUICulture = cultureFeature.RequestCulture.UICulture
            };
            return View(model);
        }
    }
}

Views/Attachment/Add.cshtml
@using Microsoft.AspNetCore.Localization

@using Microsoft.Extensions.Localization;
@inject WebUI.Services.CommonLocalizationService localizer

@model WebUI.ViewModel.AttachmentViewModel

<div class="col-md-12">
    <form enctype="multipart/form-data" asp-action="Create">
        <div class="panel panel-default" style="background-color:white; overflow:hidden;">
            <div class="panel-heading">@localizer.Get("UploadFile")</div>

            <div class="panel-body form-horizontal">
                <div class="form-group">
                    <label class="control-label">@localizer.Get("AttachmentName")</label>
                    <div class="custom-file">
                        <input asp-for="FileName" class="custom-file-input" id="customFile" required>
                        <label class="custom-file-label" for="customFile">@localizer.Get("Choosefile")</label>
                    </div>
                </div>
            </div>
        </div>


        <div class="form-group">
            <label class="col-sm-4 text-right">&nbsp;</label>
            <div class="col-sm-6">
                <input type="submit" value=@localizer.Get("Upload") class="btn btn-primary" /><i class="fas fa-plus-circle"></i>
                <a asp-action="Index" class="btn btn-dark"><i class="fas fa-fast-backward"></i>@localizer.Get("BackToList")</a>
            </div>
        </div>

    </form>

</div>


@section scripts{
    <script type="text/javascript">
        alert();
        // following code will appear the name on the input box
        $(".custom-file-input").on("change", function () {
            alert();
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });

    </script>
}

Views/Attachment/Create.cshtml
@using Microsoft.AspNetCore.Localization

@using Microsoft.Extensions.Localization;
@inject WebUI.Services.CommonLocalizationService localizer

@model WebUI.ViewModel.AttachmentViewModel

<div class="col-md-12">
    <form enctype="multipart/form-data" asp-action="Create">
        <div class="panel panel-default" style="background-color:white; overflow:hidden;">
            <div class="panel-heading">@localizer.Get("UploadFile")</div>

            <div class="panel-body form-horizontal">
                <div class="form-group">
                    <label class="control-label">@localizer.Get("AttachmentName")</label>
                    <div class="custom-file">
                        <input asp-for="FileName" class="custom-file-input" id="customFile" required>
                        <label class="custom-file-label" for="customFile">@localizer.Get("Choosefile")</label>
                    </div>
                </div>
            </div>
        </div>


        <div class="form-group">
            <label class="col-sm-4 text-right">&nbsp;</label>
            <div class="col-sm-6">
                <input type="submit" value=@localizer.Get("Upload") class="btn btn-primary" /><i class="fas fa-plus-circle"></i>
                <a asp-action="Index" class="btn btn-dark"><i class="fas fa-fast-backward"></i>@localizer.Get("BackToList")</a>
            </div>
        </div>

    </form>

</div>


@section scripts{
    <script type="text/javascript">
        
        // following code will appear the name on the input box
        $(".custom-file-input").on("change", function () {
            
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });

    </script>
}

Views/Attachment/Index.cshtml
@inject WebUI.Services.CommonLocalizationService localizer

@model IEnumerable<Attachment>

<hr />
<div class="col-xs-6 no-padding ">
    <a asp-action="Create" class="btn btn-primary"><i class="fas fa-plus-circle"></i>@localizer.Get("UploadAttachments")</a>
</div>

<br />

<div class="panel panel-default" style="background-color:white; overflow:hidden;">
    <div class="panel-body">
        <table class="table table-hover">
            <thead>
                <tr class="fontHeading">
                    <th class="text-center">
                        @localizer.Get("AttachmentName")
                    </th>
                    <th class="text-center">
                        @localizer.Get("Path")
                    </th>
                    <th class="text-center">
                        @localizer.Get("Entry Date")
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-center fontRows">
                        <td class="text-center">
                            @Html.DisplayFor(m => item.FileName)
                        </td>
                        <td class="text-center">
                            @Html.DisplayFor(m => item.Path)
                        </td>
                        <td class="text-center">
                            @Html.DisplayFor(m => item.EntryDate)
                        </td>                      
                    </tr>
                }
                @if (!Model.Any())
                {
                    <tr>
                        <td colspan="3">@localizer.Get("NoRecordsFound")</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sample Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Attachment" asp-action="Index"></a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Sample Project - @*<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>